version: '3.0'
services:
  conan_server:
    hostname: conan_server
    container_name: conan_server
    image: python:3.9.19-bullseye
    ports:
      - "9300:9300"
    volumes:
      - ./containers:/containers
    entrypoint: ./containers/conan_server.sh

  library_builder:
    container_name: library_builder
    build:
      context: .
      dockerfile: ./containers/Dockerfile
    volumes:
      - ./conan_library:/conan_library
      - ./containers:/containers
    entrypoint: ./containers/library_builder.sh

  application_builder:
    container_name: application_builder
    build:
      context: .
      dockerfile: ./containers/Dockerfile
    volumes:
      - ./conan_application:/conan_application
      - ./containers:/containers
    entrypoint: ./containers/application_builder.sh
    environment:
      - BUILD_FROM_SOURCE=0
  
  development:
    container_name: development
    build:
      context: .
      dockerfile: ./containers/Dockerfile
    volumes:
      - ./conan_library:/conan_library
      - ./conan_application:/conan_application
      - ./containers:/containers
    entrypoint: /bin/bash
